#! /usr/bin/env nix-shell
#! nix-shell -i bash -p jq wget

rm -r javascript/generated
hfile="src/Eventlog/AssetVersions.hs"
echo "-- Generated by ./update-assets.sh" > $hfile
echo "module Eventlog.AssetVersions where" >> $hfile

for row in $(cat versions.json | jq -r '.[] | @base64'); do
  _jq(){
    echo ${row} | base64 --decode | jq -r ${1}
  }

  version=$(_jq '.version')
  raw_url=$(_jq '.url')
  raw_name=$(_jq '.hname')
  url=${raw_url/<>/$version}
  wget -P javascript/generated $url
  echo "${raw_name}Version,${raw_name}URL :: String" >> $hfile
  echo "${raw_name}Version = \"$version\"" >> $hfile
  echo "${raw_name}URL = \"$url\"" >> $hfile

done


